import React, { Component } from 'react';
import styles from '../../styles'
import { Dimensions }       from 'react-native';
import Image from 'react-native-scalable-image';

const { width, height } = Dimensions.get('window');

export const animalGifs = [
  <Image
     key="horse"
     width={width}
     source={require('../../assets/images/horse.gif')}
     style={styles.zooImage}
  />,
   <Image
       key="polarBear"
       width={width}
       source={require('../../assets/images/polarBear.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="giraffe"
       width={width}
       source={require('../../assets/images/giraffe.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="elephant"
       width={width}
       source={require('../../assets/images/elephant.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="zebra"
       width={width}
       source={require('../../assets/images/zebra.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="fox"
       width={width}
       source={require('../../assets/images/fox.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="kitten"
       width={width}
       source={require('../../assets/images/kitten.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="lamb"
       width={width}
       source={require('../../assets/images/lamb.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="squirrel"
       width={width}
       source={require('../../assets/images/squirrel.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="horse-water-bucket"
       width={width}
       source={require('../../assets/images/horse-water-bucket.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="prarie-dog"
       width={width}
       source={require('../../assets/images/prarie-dog.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="penguin"
       width={width}
       source={require('../../assets/images/penguin.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="peacock"
       width={width}
       source={require('../../assets/images/peacock.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="panda"
       width={width}
       source={require('../../assets/images/panda.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="otter"
       width={width}
       source={require('../../assets/images/otter.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="meerkat"
       width={width}
       source={require('../../assets/images/meerkat.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="lions"
       width={width}
       source={require('../../assets/images/lions.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="lemur"
       width={width}
       source={require('../../assets/images/lemur.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="koala"
       width={width}
       source={require('../../assets/images/koala.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="kangaroo"
       width={width}
       source={require('../../assets/images/kangaroo.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="hummingbird"
       width={width}
       source={require('../../assets/images/hummingbird.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="hippo"
       width={width}
       source={require('../../assets/images/hippo.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="hawk-squirrel"
       width={width}
       source={require('../../assets/images/hawk-squirrel.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="gorilla"
       width={width}
       source={require('../../assets/images/gorilla.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="frog"
       width={width}
       source={require('../../assets/images/frog.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="cow"
       width={width}
       source={require('../../assets/images/cow.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="chicken"
       width={width}
       source={require('../../assets/images/chicken.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="cheetah"
       width={width}
       source={require('../../assets/images/cheetah.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="camel"
       width={width}
       source={require('../../assets/images/camel.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="bald-eagle"
       width={width}
       source={require('../../assets/images/bald-eagle.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="baby-seal-waddling"
       width={width}
       source={require('../../assets/images/baby-seal-waddling.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="anteater"
       width={width}
       source={require('../../assets/images/anteater.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="rhino"
       width={width}
       source={require('../../assets/images/rhino.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="sea-turtle"
       width={width}
       source={require('../../assets/images/sea-turtle.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="seal"
       width={width}
       source={require('../../assets/images/seal.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="sloth"
       width={width}
       source={require('../../assets/images/sloth.gif')}
       style={styles.zooImage}
   />,
   <Image
       key="whale-splash"
       width={width}
       source={require('../../assets/images/whale-splash.gif')}
       style={styles.zooImage}
   />,


];
